Update reusable_terraform.yml

diff --git a/.github/workflows/reusable_terraform.yml b/.github/workflows/reusable_terraform.yml
--- a/.github/workflows/reusable_terraform.yml
+++ b/.github/workflows/reusable_terraform.yml
@@ -40,7 +40,7 @@ jobs:
           environment=$(echo "${{ inputs.Environment }}" | tr '[:upper:]' '[:lower:]')
           terraform_files=("main.tf" "backend.tf" "providers.tf" "data.tf" "variables.tf" "outputs.tf")
           config_files=("./config/aws.yml" "./config/product.yml" "./config/env/$environment.yml")
-          required_directories=("./config/deploykeys")
+          required_directories=("./config/deploykeys", "./config/keypairs")
           for file in "${terraform_files[@]}"; do
             if [ ! -f "$file" ]; then
               echo "Error: Required Terraform file not found: $file"
@@ -97,6 +97,27 @@ jobs:
             exit 1
           fi
           echo "✅ Product and Environment names Passed"
+      - name: KeyPairs Check
+        run: |
+
+          KEYPAIRS=("./config/keypairs/*")
+
+          if (( ${#KEYPAIRS[@]} == 0 )); then
+            echo "❌ No KeyPairs Found in $KEYPAIRS."
+            exit 1
+          fi
+
+          for keyfile in "${KEYPAIRS[@]}"; do
+            echo "🔍 Checking $keyfile..."
+            if ssh-keygen -l -f "$keyfile" &>/dev/null; then
+              echo "✔️  $keyfile: Public Key OK"
+            else
+              echo "🚫 $keyfile: Public Key ERROR" >&2
+              exit 1
+            fi
+          done
+
+          echo "✅ Keypairs Passed"
       - name: Extract ./config/deploykeys/*
         id: LoadDeployKeys
         run: |
