Update ReusableTerraform.yml

diff --git a/.github/workflows/ReusableTerraform.yml b/.github/workflows/ReusableTerraform.yml
--- a/.github/workflows/ReusableTerraform.yml
+++ b/.github/workflows/ReusableTerraform.yml
@@ -12,9 +12,6 @@ on:
       Stage:
         required: true
         type: string
-      Repo:
-        required: true
-        type: string
       Environment:
         required: true
         type: string
@@ -42,50 +39,76 @@ jobs:
       uses: actions/checkout@v4
     - name: Validate required files
       run: |
-        environment=$(echo "${{ inputs.Environment }}" | tr '[:upper:]' '[:lower:]')
+        ENVIRONMENT=$(echo "${{ inputs.Environment }}" | tr '[:upper:]' '[:lower:]')
         required_files=(
-          main.tf config.tf outputs.tf variables_product.tf variables_env.tf
-          ./config/cicd.yml ./config/product.yml ./config/env/$environment.yml
+          main.tf
+          providers.tf
+          backend.tf
+          outputs.tf
+          variables.json
+          variables.tf
+          ./environments/$ENVIRONMENT.tfvars.json
+          ./environments/$ENVIRONMENT.tf
         )
         for file in "${required_files[@]}"; do
           [[ -f "$file" ]] || { echo "❌ Missing required file: $file"; exit 1; }
         done
         echo "✅ All required files are present"
-    - name: Validate minimal keys in product.yml
+    - name: Validate minimal keys in variables.json
       run: |
-        for key in Product Network Ec2; do
-          grep -qE "^[[:space:]]*${key}:" ./config/product.yml \
-            && echo "✅ Key '$key' exists" \
-            || { echo "❌ ERROR: Missing key '$key'"; exit 1; }
+        VARIABLES_FILE="variables.json"
+        REQUIRED_KEYS=(
+          ".CiCd.Project"
+          ".CiCd.Repo"
+          ".CiCd.Region"
+          ".CiCd.Role"
+          ".CiCd.BackendBucket"
+          ".Project.Network"
+          ".Project.Ec2"
+        )
+        for key in "${REQUIRED_KEYS[@]}"; do
+          value=$(jq -r "$key // empty" "$VARIABLES_FILE")
+          if [[ -z "$value" || "$value" == "null" ]]; then
+            echo "❌ ERROR: Missing key $key" ; exit 1
+          fi
         done
-    - name: Validate minimal keys in cicd.yml
+        echo "✅ All required Keys exists"
+    - name: Validate Project, Repo, Stage and Environment format
       run: |
-        for key in Region Role BackendBucket DeployKeys; do
-          grep -qE "^[[:space:]]*${key}:" ./config/cicd.yml \
-            && echo "✅ Key '$key' exists" \
-            || { echo "❌ ERROR: Missing key '$key'"; exit 1; }
-        done
-    - name: Validate Product, Stage and Environment format
-      run: |
-        product=$(yq e '.Product' ./config/product.yml)
-        [[ "$product" =~ ^[A-Z] ]] || { echo "❌ Product must start with a capital letter (Found: '$product')"; exit 1; }
-        case "${{ inputs.Environment }}" in
-          Prod|Dev) echo "✅ Environment '${{ inputs.Environment }}' is valid" ;;
-          *) echo "❌ Invalid Environment: ${{ inputs.Environment }}"; exit 1 ;;
-        esac
-        case "${{ inputs.Stage }}" in
-          Workload|Concept)
-            echo "✅ Stage '${{ inputs.Stage }}' is valid"
-            ;;
-          *)
-            echo "❌ Invalid Stage: ${{ inputs.Stage }} (must be 'Workload' or 'Poc')"
-            exit 1
-            ;;
-        esac
-        echo "✅ Product '$product' is valid"
-        echo "✅ Environment '${{ inputs.Environment }}' is valid"
-        echo "✅ Stage '${{ inputs.Stage }}' is valid"
-        
+        VARIABLES_FILE="variables.json"
+        PROJECT=$(jq -r '.CiCd.Project' "$VARIABLES_FILE")
+        REPO=$(jq -r '.CiCd.Repo' "$VARIABLES_FILE")
+        ENVIRONMENT="${{ inputs.Environment }}"
+        STAGE="${{ inputs.Stage }}"
+
+        # Validar que .CiCd.Project comience con mayúscula
+        if [[ ! "$PROJECT" =~ ^[A-Z] ]]; then
+          echo "❌ Project must start with a capital letter (actual: \"$PROJECT\")"
+          exit 1
+        fi
+
+        # Validar que .CiCd.Repo comience con mayúscula
+        if [[ ! "$REPO" =~ ^[A-Z] ]]; then
+          echo "❌ Repo must start with a capital letter (actual: \"$REPO\")"
+          exit 1
+        fi
+
+        # Validar que Environment sea solo "Prod" o "Dev"
+        if [[ "$ENVIRONMENT" != "Prod" && "$ENVIRONMENT" != "Dev" ]]; then
+          echo "❌ Invalid Environment: (actual: \"$ENVIRONMENT\")"
+          exit 1
+        fi
+
+        # Validar que Stage sea solo "Workload" o "Concept"
+        if [[ "$STAGE" != "Workload" && "$STAGE" != "Concept" ]]; then
+          echo "❌ Invalid Stage: (actual: \"$STAGE\")"
+          exit 1
+        fi
+
+        echo "✅ Project Name '$PROJECT' is valid"
+        echo "✅ Repo Name '$REPO' is valid"
+        echo "✅ Environment '$ENVIRONMENT' is valid"
+        echo "✅ Stage '$STAGE' is valid"
   ExtractConfig:
     runs-on: ${{ inputs.Runner }}
     permissions:
@@ -97,36 +120,36 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-      - name: Load product.yml
-        id: ProductYml
+      - name: Load Project.yml
+        id: ProjectJson
         run: |
-          CONTENT=$(yq e -o=json ./config/product.yml | jq -c .)
-          echo "Yml=$CONTENT" >> $GITHUB_OUTPUT
-      - name: Load product
-        id: Product
+          VARIABLES_FILE="variables.json"
+          PROJECT=$(jq -c '.Project' "$VARIABLES_FILE")
+          echo "JSON=$PROJECT" >> $GITHUB_OUTPUT
+      - name: Load CiCd Data
+        id: CiCdJson
         run: |
-          CONTENT=$(yq e -o=json ./config/product.yml | jq -c .)
-          PRODUCT=$(echo "$CONTENT" | jq -r '.Product')
-          echo "PRODUCT=$PRODUCT" >> $GITHUB_OUTPUT
-      - name: Load cicd.yml
-        id: CiCdYml
-        run: |
-          CONTENT=$(yq e -o=json ./config/cicd.yml)
-          REGION=$(echo "$CONTENT" | jq -r '.Region')
-          ROLE=$(echo "$CONTENT" | jq -r '.Role')
-          BACKENDBUCKET=$(echo "$CONTENT" | jq -r '.BackendBucket')
-          DEPLOYKEYS=$(echo "$CONTENT" | jq -c '.DeployKeys')
+          VARIABLES_FILE="variables.json"
+          PROJECT=$(jq -r '.CiCd.Project' "$VARIABLES_FILE")
+          REPO=$(jq -r '.CiCd.Repo' "$VARIABLES_FILE")
+          REGION=$(jq -r '.CiCd.Region' "$VARIABLES_FILE")
+          ROLE=$(jq -r '.CiCd.Role' "$VARIABLES_FILE")
+          BACKENDBUCKET=$(jq -r '.CiCd.BackendBucket' "$VARIABLES_FILE")
+          DEPLOYKEYS=$(jq -c '.CiCd.DeployKeys' "$VARIABLES_FILE")
+          echo "PROJECT=$PROJECT" >> $GITHUB_OUTPUT
+          echo "REPO=$REPO" >> $GITHUB_OUTPUT
           echo "REGION=$REGION" >> $GITHUB_OUTPUT
           echo "ROLE=$ROLE" >> $GITHUB_OUTPUT
           echo "BACKENDBUCKET=$BACKENDBUCKET" >> $GITHUB_OUTPUT
           echo "DEPLOYKEYS=$DEPLOYKEYS" >> $GITHUB_OUTPUT
     outputs:
-      ProductYml: ${{ steps.ProductYml.outputs.Yml }}
-      Product: ${{ steps.Product.outputs.PRODUCT }}
-      CiCdRegion: ${{ steps.CiCdYml.outputs.REGION }}
-      CiCdRole: ${{ steps.CiCdYml.outputs.ROLE }}
-      CiCdBackendBucket: ${{ steps.CiCdYml.outputs.BACKENDBUCKET }}
-      CiCdDeployKeys: ${{ steps.CiCdYml.outputs.DEPLOYKEYS }}
+      ProjectJson: ${{ steps.ProjectJson.outputs.JSON }}
+      Project: ${{ steps.CiCdJson.outputs.PROJECT }}
+      Repo: ${{ steps.CiCdJson.outputs.REPO }}
+      CiCdRegion: ${{ steps.CiCdJson.outputs.REGION }}
+      CiCdRole: ${{ steps.CiCdJson.outputs.ROLE }}
+      CiCdBackendBucket: ${{ steps.CiCdJson.outputs.BACKENDBUCKET }}
+      CiCdDeployKeys: ${{ steps.CiCdJson.outputs.DEPLOYKEYS }}
 
   ParseSShKey:
     runs-on: ${{ inputs.Runner }}
@@ -164,10 +187,10 @@ jobs:
           path: deploykeys/
       - name: Validate Keypairs
         run: |
-          KEYPAIRS=$(echo '${{ needs.ExtractConfig.outputs.ProductYml }}' | jq -r '.Ec2.KeyPairs | keys[]')
+          KEYPAIRS=$(echo '${{ needs.ExtractConfig.outputs.ProjectJson }}' | jq -r '.Ec2.KeyPairs | keys[]')
           for KEY in $KEYPAIRS; do
             echo "🔑 Validando clave: $KEY"
-            BASE64_KEY=$(echo '${{ needs.ExtractConfig.outputs.ProductYml }}' | jq -r ".Ec2.KeyPairs[\"$KEY\"]")
+            BASE64_KEY=$(echo '${{ needs.ExtractConfig.outputs.ProjectJson }}' | jq -r ".Ec2.KeyPairs[\"$KEY\"]")
             echo "$BASE64_KEY" | base64 -d > decoded_key 2>/dev/null
             if ssh-keygen -l -f decoded_key >/dev/null 2>&1; then
               echo "✅ $KEY is valid"
@@ -193,42 +216,46 @@ jobs:
         run: |
           cat <<EOF > backend.tfbackend
             bucket = "${{ needs.ExtractConfig.outputs.CiCdBackendBucket }}"
-            key    = "${{ format('{0}{1}.tfstate', needs.ExtractConfig.outputs.Product, inputs.Stage) }}"
+            key    = "${{ format('{0}{1}.tfstate', needs.ExtractConfig.outputs.Project, inputs.Stage) }}"
             region = "${{ needs.ExtractConfig.outputs.CiCdRegion }}"
           EOF
-      - name: Create empty vars.json
-        run: echo "{}" > vars.json
-      - name: Append Product String > vars.json
+      - name: Create empty variables.tfvars.json
+        run: echo "{}" > variables.tfvars.json
+      - name: Append Project String > variables.tfvars.json
         run: |
-          jq --arg product "${{ needs.ExtractConfig.outputs.Product }}" '. + {Product: $product}' vars.json > tmp.json && mv tmp.json vars.json
-      - name: Append Stage String > vars.json
+          jq --arg Project "${{ steps.CiCdJson.outputs.PROJECT }}" '. + {Project: $Project}' variables.tfvars.json > tmp.json && mv tmp.json variables.tfvars.json
+      - name: Append Repo String > variables.tfvars.json
         run: |
-          jq --arg stage "${{ inputs.Stage }}" '. + {Stage: $stage}' vars.json > tmp.json && mv tmp.json vars.json
-      - name: Append Product Yml > vars.json
+          jq --arg Project "${{ steps.CiCdJson.outputs.REPO }}" '. + {Repo: $Repo}' variables.tfvars.json > tmp.json && mv tmp.json variables.tfvars.json
+      - name: Append Stage String > variables.tfvars.json
         run: |
-          VARS='${{ needs.ExtractConfig.outputs.ProductYml }}'
+          jq --arg stage "${{ inputs.Stage }}" '. + {Stage: $stage}' variables.tfvars.json > tmp.json && mv tmp.json variables.tfvars.json
+      - name: Append variables.json Project > variables.tfvars.json
+        run: |
+          VARS='${{ needs.ExtractConfig.outputs.ProjectJson }}'
           added_count=$(echo "$VARS" | jq 'keys | length')
-          jq -s '.[0] * .[1]' vars.json <(echo "$VARS") > tmp.json && mv tmp.json vars.json
-          echo "✅ $added_count variables added from iProductYml to vars.json"
-      - name: Append environment variables > vars.json
+          jq -s '.[0] * .[1]' variables.tfvars.json <(echo "$VARS") > tmp.json && mv tmp.json variables.tfvars.json
+          echo "✅ $added_count variables added from Variables Project to variables.tfvars.json"
+      - name: Append environment variables > variables.tfvars.json
         run: |
-          VARS="./config/env/$(echo "${{ inputs.Environment }}" | tr '[:upper:]' '[:lower:]').yml"
-          added_count=$(yq -o=json "$VARS" | jq 'keys | length')
-          jq -s '.[0] * .[1]' vars.json <(yq -o=json "$VARS") > tmp.json && mv tmp.json vars.json
-          echo "✅ $added_count variables added from $env_file to vars.json"
-      - name: Append inputs.ExtraVars > vars.json
+          ENVIRONMENT=$(echo "${{ inputs.Environment }}" | tr '[:upper:]' '[:lower:]')
+          VARS="./environments/$ENVIRONMENT.json"
+          added_count=$(jq 'keys | length' "$VARS")
+          jq -s '.[0] * .[1]' variables.tfvars.json "$VARS" > tmp.json && mv tmp.json variables.tfvars.json
+          echo "✅ $added_count variables added from $VARS to variables.tfvars.json"
+      - name: Append inputs.ExtraVars > variables.tfvars.json
         run: |
           VARS='${{ inputs.ExtraVars }}'
           added_count=$(echo "$VARS" | jq 'keys | length')
-          jq -s '.[0] * .[1]' vars.json <(echo "$VARS") > tmp.json && mv tmp.json vars.json
-          echo "✅ $added_count variables added from inputs.ExtraVars to vars.json"
+          jq -s '.[0] * .[1]' variables.tfvars.json <(echo "$VARS") > tmp.json && mv tmp.json variables.tfvars.json
+          echo "✅ $added_count variables added from inputs.ExtraVars to variables.tfvars.json"
       - name: Upload Terraform config files
         uses: actions/upload-artifact@v4
         with:
           name: TfFiles
           path: |
             backend.tfbackend
-            vars.json
+            variables.tfvars.json
 
   Apply:
     runs-on: ${{ inputs.Runner }}
@@ -283,7 +310,7 @@ jobs:
         timeout-minutes: 1
       - name: Terraform Plan
         id: TerraformPlan
-        run: terraform plan -var-file=vars.json -no-color
+        run: terraform plan -var-file=variables.tfvars.json -no-color
         timeout-minutes: 1
       - name: Manual Workflow Approval
         uses: trstringer/manual-approval@v1.9.1
@@ -291,7 +318,7 @@ jobs:
         with:
           secret: ${{ github.TOKEN }}
           approvers: ${{ github.actor }}
-          issue-title: "Terraform Apply to Product ${{ steps.ProductYml.outputs.Product }} in Env ${{ inputs.Environment }}"
+          issue-title: "Terraform Apply to Project ${{ steps.ProjectJson.outputs.Project }} in Env ${{ inputs.Environment }}"
           issue-body: |
             Plan output:
 
@@ -302,7 +329,7 @@ jobs:
           additional-approved-words: 'allow'
           additional-denied-words: 'deny'
       - name: Terraform Apply
-        run: terraform apply -auto-approve -var-file=vars.json
+        run: terraform apply -auto-approve -var-file=variables.tfvars.json
       - name: Terraform Output
         id: TerraformOutput
         run: TerraformOutput=$(terraform output -json | jq -c 'with_entries(.value = .value.value)') ; echo "TerraformOutput=$TerraformOutput" >> $GITHUB_OUTPUT
